= Feedback

// tag::intro[]

[.tagline]
A simple to use feedback system for CMake based C++ projects.

[horizontal.shields]

// end::intro[]

== License

// tag::license[]

Distributed under the [MIT](https://opensource.org/licenses/MIT) license.

// end::license[]

== Features

// tag::features[]

* Define new feedback rules within minutes

// end::features[]

== Design Goals

// tag::goals[]

* Simple
* Fast

// end::goals[]

== Using

// tag::using[]

To use, integrate the feedback system into your CMake project:

[source,cmake]
----
include (FetchContent)

FetchContent_Declare (feedback_content GIT_REPOSITORY "https://github.com/volumegraphics/feedback.git" GIT_TAG 1.0.0)
FetchContent_MakeAvailable (feedback_content)
----

You can also add feedback as subdirectory if you store its sources side-by-side:

[source,cmake]
----
add_subdirectory (path_to_feedback)
----

A feedback can then be added to your targets like this:

[source,cmake]
----
add_library (example ...)

# Recommended setting to group feedback targets
set_property(GLOBAL PROPERTY USE_FOLDERS true)

Feedback_Add (coding_guidelines RULES rules.json DIRECTORIES "${CMAKE_SOURCE_DIR}")
----

This will add the `coding_guidelines` feedback to all targets (executables, static, shared and module libraries) which will be built in CMAKE_SOURCE_DIR or its subdirectories.
Imported targets will be ignored.

You can also select the targets explicitly

[source,cmake]
----
Feedback_Add (coding_guidelines RULES rules.json TARGETS example)
----

or control the types of targets which will be included

[source,cmake]
----
# omit executables from feedback
Feedback_FindTargets (targets DIRECTORIES "${CMAKE_SOURCE_DIR}" TYPES STATIC_LIBRARY MODULE_LIBRARY SHARED_LIBRARY)
Feedback_Add (coding_guidelines RULES rules.json TARGETS ${targets})
----

You can exclude certain targets from feedback:

[source,cmake]
----
add_executable (ignored ...)
Feedback_Exclude (ignored)

Feedback_Add (CodingGuidelines RULES rules.json DIRECTORIES "${CMAKE_SOURCE_DIR}")
----

The feedback rules (`rules.json`) of our `coding_guidelines` feedback could look similar to this:

[source,json]
----
{
  "RULE1": {
    "type": "requirement",
    "matched_files": "[.](c|cc|cpp|cxx|h|i)([.]in)?$",
    "matched_text": "\t",
    "summary": "Don't use tabulators in source files",
    "rationale": "Developers who use spaces make more money than those who use tabs. See also: https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/",
    "workaround": "Please replace all tabulators with spaces and adjust your editor settings accordingly."
  },
  "RULE2": {
    "type": "guideline",
    "matched_files": "[.](c|cc|cpp|cxx|h|i)([.]in)?$",
    "matched_text": "^ *# *include *([<][^>]*|[\"][^\"]*)[\\\\]",
    "marked_text": "[\\\\]",
    "summary": "Don't use backslashes in include directives",
    "rationale": "Non Windows systems may not recognize a backslash as path delimiter.",
    "workaround": "Please replace all backslashes with forward slashes in include directives."
  },
  "RULE3": {
    "type": "improvement",
    "matched_files": "[.](c|cc|cpp|cxx|h|i)([.]in)?$",
    "matched_text": "^ *# *include *([<][^>]*|[\"][^\"]*)//",
    "marked_text": "//",
    "summary": "Duplicate forward slash in include directive",
    "rationale": "Such typos are ignored by most compilers, but they complicate automated refactorings.",
    "workaround": "Please remove the redundant forward slash."
  },
  "RULE4": {
    "type": "suggestion",
    "matched_files": "[.](c|cc|cpp|cxx|h|i)([.]in)?$",
    "matched_text": "// *(TODO|FIXME|REVIEW|OPTIMIZE|HACK|XXX|BUG)",
    "marked_text": "[A-Z]+",
    "summary": "Unfinished task (TODO/FIXME/HACK/...)",
    "rationale": "Task markers should be used only rarely and temporarily because they indicate a technical debt and will be forgotton eventually.",
    "workaround": "Please finish this task if possible. Remove its marker from our code base either way. Use an issue tracker like JIRA for important tasks."
  }
}
----

// end::using[]
